// Generated by Wrangler by running `wrangler types`

import { D1Database, R2Bucket } from '@cloudflare/workers-types/experimental'

export interface Env {
  DB: D1Database
  BUCKET: R2Bucket
  requestId: string
  method: string
  functionPath: string
  location: string
}

interface ApiResponse<T = never> {
  code: number
  data: T | null
  msg: string
}
