// Generated by Wrangler by running `wrangler types`

import { D1Database, R2Bucket } from '@cloudflare/workers-types/experimental'

export interface Env {
  DB: D1Database
  BUCKET: R2Bucket
  requestId: string
  method: string
  functionPath: string
  location: string
  word: string
}

interface ApiResponse<T = never> {
  code?: number
  data?: T | null
  msg?: string
}

export interface Keyword {
  id: number
  word: string
  password: string
  files_size: number
  expire_time: string
  create_time: string
  update_time: string
  random_key: string
  last_view_time: string
  view_count: number
}
